import {commercialOverview} from './commercial-overview.js';
import {orderStatus} from './payment-detail.js';
export const subscriptionStatus=(s,now=Date.now())=>Date.parse(s.starts_at)>now?'À venir':Date.parse(s.ends_at)>now?'En cours':'Terminé';
const date=value=>value?new Date(value).toLocaleString('fr-FR'):'—';
export async function recordsPanel(area,tab,{api,esc,money,admin=false}){
 const data=await api(admin?'admin':'client');
 const clients=new Map((data.clients||[]).map(c=>[c.id,c.name]));
 const organization=id=>clients.get(id)||'Activité indisponible';
 const card=(title,body)=>'<article class="record-card"><strong>'+esc(title)+'</strong>'+body+'</article>';
 let records=[];
 if(tab==='Clients')records=data.clients.map(c=>{const owner=data.members.find(m=>m.org_id===c.id&&m.role==='owner'),profile=data.profiles?.find(p=>p.id===owner?.user_id),vehicles=(data.vehicles||[]).filter(v=>v.org_id===c.id);return {status:owner?.active?'Actif':'Désactivé',search:c.name+' '+(profile?.display_name||'')+' '+(profile?.phone||''),html:card(c.name,'<p>Inscrit le '+esc(date(c.created_at))+'</p><p>'+esc(data.subscriptions.filter(s=>s.org_id===c.id&&subscriptionStatus(s)==='En cours').map(s=>s.plan_id).join(', ')||'Aucun abonnement actif')+'</p><span>'+data.orders.filter(o=>o.org_id===c.id).length+' commande(s)</span><details><summary>Consulter le client</summary><p>'+esc(profile?.display_name||'Nom non renseigné')+' · '+esc(profile?.phone||'Téléphone non renseigné')+'</p><p>Compte '+(owner?.active?'actif':'désactivé')+'</p><p>'+data.members.filter(m=>m.org_id===c.id&&m.role==='viewer'&&m.active).length+' lecteur(s) actif(s)</p><h3>Véhicules</h3>'+vehicles.map(v=>'<p>'+esc(v.name)+' · '+esc(v.plate)+'</p>').join('')+'<h3>Commandes</h3>'+data.orders.filter(o=>o.org_id===c.id).map(o=>'<p>'+esc(o.reference)+' · '+esc(orderStatus[o.status]||o.status)+' · '+money(o.total)+'</p>').join('')+'</details>')};});
 if(tab==='Abonnements')records=data.subscriptions.slice().sort((a,b)=>b.ends_at.localeCompare(a.ends_at)).map(s=>({status:subscriptionStatus(s),search:organization(s.org_id)+' '+s.plan_id,html:card(organization(s.org_id),'<b>'+esc(s.plan_id)+'</b><span>'+subscriptionStatus(s)+'</span><p>'+esc(date(s.starts_at))+' → '+esc(date(s.ends_at))+'</p>')}));
 if(tab==='Lecteurs')records=data.members.filter(m=>m.role==='viewer').map(m=>({status:m.active?'Actif':'Révoqué',search:organization(m.org_id)+' '+m.user_id,html:card(organization(m.org_id),'<span>'+(m.active?'Actif':'Révoqué')+'</span><p>'+(m.all_vehicles?'Tous les véhicules':'Véhicules attribués par le propriétaire')+'</p><small>Identifiant : '+esc(m.user_id)+'</small>')}));
 if(tab==='Journal')records=data.audit.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(a=>({search:organization(a.org_id)+' '+a.action,html:card(a.action,'<span>'+esc(date(a.created_at))+'</span><p>'+esc(a.org_id?organization(a.org_id):'Administration générale')+'</p><small>Événement '+esc(a.id)+'</small>')}));
 if(tab==='Paiements')records=data.payments.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(p=>{const order=data.orders.find(o=>o.id===p.order_id);return {status:orderStatus[order?.status]||order?.status||'',search:p.reference+' '+(order?.reference||''),html:card(order?.reference||'Commande','<span>'+esc(orderStatus[order?.status]||order?.status||'')+'</span><p>Référence transmise : '+esc(p.reference)+'</p><b>'+money(order?.total??0)+'</b><p>'+esc(date(p.created_at))+'</p><a class="button" href="/paiement?order='+encodeURIComponent(p.order_id)+'">Consulter le paiement et son justificatif</a>')};});
 if(tab==='Statistiques'){area.innerHTML='<h2>Statistiques commerciales</h2>'+commercialOverview(data,{esc,money});return;}
 const statuses=[...new Set(records.map(r=>r.status).filter(Boolean))];
 area.innerHTML='<section class="panel"><h2>'+esc(tab)+'</h2>'+'<div class="filters"><label>Rechercher<input id="record-search" type="search"></label>'+(statuses.length?'<label>Statut<select id="record-status"><option value="">Tous</option>'+statuses.map(s=>'<option>'+esc(s)+'</option>').join('')+'</select></label>':'')+'</div><div id="record-results"></div><div class="actions"><button id="record-prev">Précédent</button><span id="record-count" aria-live="polite"></span><button id="record-next">Suivant</button></div></section>';
 let page=0;const size=20;
 const render=()=>{const query=area.querySelector('#record-search').value.trim().toLocaleLowerCase('fr'),status=area.querySelector('#record-status')?.value,filtered=records.filter(r=>(!status||r.status===status)&&r.search.toLocaleLowerCase('fr').includes(query));const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages-1);area.querySelector('#record-results').innerHTML=filtered.slice(page*size,(page+1)*size).map(r=>r.html).join('')||'<p>Aucun résultat.</p>';area.querySelector('#record-count').textContent=filtered.length+' résultat(s) · '+(page+1)+' / '+pages;area.querySelector('#record-prev').disabled=page===0;area.querySelector('#record-next').disabled=page===pages-1;};
 area.querySelector('#record-search').oninput=()=>{page=0;render();};if(statuses.length)area.querySelector('#record-status').onchange=()=>{page=0;render();};area.querySelector('#record-prev').onclick=()=>{page--;render();};area.querySelector('#record-next').onclick=()=>{page++;render();};render();
}
