export async function commercialPanel(area,tab,{api,esc,money}){
 const data=await api('admin');
 const refresh=()=>commercialPanel(area,tab,{api,esc,money});
 const run=async(action,body)=>{try{await api(action,body);await refresh();}catch(e){area.querySelector('[role=alert]').textContent=e.message;}};
 let content='';
 if(tab==='Paramètres')content=`<form id="commercial-settings"><h2>Règles commerciales</h2><p>Les tarifs officiels sont conservés. Définissez explicitement la capacité de lecteurs par formule.</p>${data.plans.map(p=>`<fieldset data-plan="${esc(p.id)}"><legend>${esc(p.id)}</legend><label>Nombre de lecteurs<input name="limit" type="number" min="0" max="10000" value="${p.secondary_user_limit??''}" placeholder="Non défini"></label><label><input name="unlimited" type="checkbox" ${p.secondary_users_unlimited?'checked':''}> Nombre illimité</label></fieldset>`).join('')}<label>Changement de formule<select name="planChange"><option value="">Validation au cas par cas</option><option value="at_expiry" ${data.settings[0]?.plan_change==='at_expiry'?'selected':''}>À l’expiration de la période en cours</option></select></label><button class="primary">Enregistrer les règles</button></form>`;
 if(tab==='Codes promo')content=`<h2>Codes promotionnels</h2><form id="promotion"><label>Nom<input name="name" required maxlength="120"></label><label>Code<input name="code" required maxlength="50"></label><label>Type<select name="type"><option value="percent">Pourcentage</option><option value="fixed">Montant KMF</option></select></label><label>Valeur<input name="value" type="number" min="0" step="1" required></label><p>Ce code sera actif, sans restriction de durée ni de nombre d’utilisations.</p><button class="primary">Créer le code</button></form>${data.promotions.map(p=>`<article class="record-card"><strong>${esc(p.code)}</strong><span>${p.type==='percent'?p.value+' %':money(p.value)}</span><p>${esc(p.name)} · ${p.active?'Actif':'Inactif'}</p></article>`).join('')}`;
 if(tab==='Commandes'||tab==='Paiements')content=`<h2>Commandes et vérification des paiements</h2>${data.orders.map(o=>{const p=data.payments.find(p=>p.order_id===o.id);return `<article class="record-card"><strong>${esc(o.reference)}</strong><span>${esc(o.status)}</span><b>${money(o.total)}</b><p>${esc(data.clients.find(c=>c.id===o.org_id)?.name||'Client')} · ${esc(p?.reference||'Aucune référence transmise')}</p>${p?.proof_path?`<button data-proof="${esc(o.id)}">Consulter le justificatif privé</button>`:''}${['declared','reviewing'].includes(o.status)?`<form data-decision="${esc(o.id)}"><label>Motif du refus, si nécessaire<input name="reason" maxlength="2000"></label><button name="decision" value="approve" class="primary">Valider et activer</button><button name="decision" value="reject">Refuser</button></form>`:''}</article>`;}).join('')||'<p>Aucune commande.</p>'}`;
 if(tab==='Avis')content=`<h2>Modération des avis</h2>${data.reviews.map(r=>`<article class="record-card"><strong>${esc(r.author_name)}</strong><b>${r.rating}/5</b><span>${esc(r.status)}</span><p>${esc(r.comment)}</p><button data-review="${esc(r.id)}" data-status="approved">Approuver</button><button data-review="${esc(r.id)}" data-status="rejected">Refuser</button><button data-review="${esc(r.id)}" data-status="hidden">Masquer</button></article>`).join('')}`;
 area.innerHTML=`<section class="panel">${content}<p role="alert" class="error"></p></section>`;
 area.querySelector('#commercial-settings')?.addEventListener('submit',e=>{e.preventDefault();const plans=[...e.target.querySelectorAll('[data-plan]')].map(f=>({id:f.dataset.plan,limit:f.querySelector('[name=limit]').value===''?null:Number(f.querySelector('[name=limit]').value),unlimited:f.querySelector('[name=unlimited]').checked}));run('commercial-settings',{plans,planChange:e.target.elements.planChange.value||null});});
 area.querySelector('#promotion')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);run('promotion',{name:f.get('name'),code:f.get('code'),type:f.get('type'),value:Number(f.get('value'))});});
 area.querySelectorAll('[data-decision]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const approve=e.submitter.value==='approve',reason=f.elements.reason.value;if(!approve&&!reason.trim()){area.querySelector('[role=alert]').textContent='Indiquez le motif du refus.';return;}run('decision',{orderId:f.dataset.decision,approve,reason});});
 area.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>run('moderate-review',{id:b.dataset.review,status:b.dataset.status}));
 area.querySelectorAll('[data-proof]').forEach(b=>b.onclick=async()=>{try{const {url}=await api('proof-read',{orderId:b.dataset.proof});const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){area.querySelector('[role=alert]').textContent=e.message;}});
}
