import {orderStatus} from './payment-detail.js';
import {promotionsPanel} from './promotions.js';
export async function commercialPanel(area,tab,{api,esc,money}){
 if(tab==='Codes promo')return promotionsPanel(area,{api,esc,money});
 const data=await api('admin');
 const refresh=()=>commercialPanel(area,tab,{api,esc,money});
 const run=async(action,body)=>{try{await api(action,body);await refresh();}catch(e){area.querySelector('[role=alert]').textContent=e.message;}};
 let content='';
 if(tab==='Paramètres')content=`<form id="commercial-settings"><h2>Règles commerciales</h2><p>Les tarifs officiels sont conservés. Définissez explicitement la capacité de lecteurs par formule.</p>${data.plans.map(p=>`<fieldset data-plan="${esc(p.id)}"><legend>${esc(p.id)}</legend><label>Nombre de lecteurs<input name="limit" type="number" min="0" max="10000" value="${p.secondary_user_limit??''}" placeholder="Non défini"></label><label><input name="unlimited" type="checkbox" ${p.secondary_users_unlimited?'checked':''}> Nombre illimité</label></fieldset>`).join('')}<label>Changement de formule<select name="planChange"><option value="">Validation au cas par cas</option><option value="at_expiry" ${data.settings[0]?.plan_change==='at_expiry'?'selected':''}>À l’expiration de la période en cours</option></select></label><button class="primary">Enregistrer les règles</button></form>`;

 if(tab==='Commandes'||tab==='Paiements')content=`<h2>Commandes et vérification des paiements</h2><div class="filters"><label>Rechercher<input id="order-search" type="search"></label><label>Statut<select id="order-status"><option value="">Tous</option>${Object.entries(orderStatus).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label></div>${data.orders.map(o=>{const p=data.payments.find(p=>p.order_id===o.id);return `<article class="record-card" data-order-status="${esc(o.status)}"><strong>${esc(o.reference)}</strong><span>${esc(orderStatus[o.status]||o.status)}</span><b>${money(o.total)}</b><p>${esc(data.clients.find(c=>c.id===o.org_id)?.name||'Client')} · ${esc(p?.reference||'Aucune référence transmise')} · ${esc(data.methods.find(m=>m.id===o.method)?.name||o.method)}</p>${p?.proof_path?`<button data-proof="${esc(o.id)}">Consulter le justificatif privé</button>`:''}${['declared','reviewing'].includes(o.status)?`<form data-decision="${esc(o.id)}"><label>Motif du refus, si nécessaire<input name="reason" maxlength="2000"></label><button name="decision" value="approve" class="primary">Valider et activer</button><button name="decision" value="reject">Refuser</button></form>`:''}</article>`;}).join('')||'<p>Aucune commande.</p>'}`;
 if(tab==='Avis')content=`<h2>Modération des avis</h2>${data.reviews.map(r=>`<article class="record-card"><strong>${esc(r.author_name)}</strong><b>${r.rating}/5</b><span>${esc(r.status)}</span><p>${esc(r.comment)}</p><button data-review="${esc(r.id)}" data-status="approved">Approuver</button><button data-review="${esc(r.id)}" data-status="rejected">Refuser</button><button data-review="${esc(r.id)}" data-status="hidden">Masquer</button></article>`).join('')}`;
 if(tab==='Moyens de paiement')content='<h2>Moyens de paiement manuels</h2><p>Les instructions ci-dessous sont présentées au Client. Wakati et la carte restent indisponibles sans intégration réelle.</p>'+data.methods.map(m=>'<form data-method="'+esc(m.id)+'"><h3>'+esc(m.name)+'</h3><label>Statut<select name="status">'+[['active','Disponible · vérification manuelle'],['disabled','Indisponible'],['soon','Bientôt disponible']].map(([value,label])=>'<option value="'+value+'" '+(m.status===value?'selected':'')+' '+(['card','wakati'].includes(m.id)&&value==='active'?'disabled':'')+'>'+label+'</option>').join('')+'</select></label><label>Instructions<textarea name="instructions" required maxlength="4000">'+esc(m.instructions)+'</textarea></label><button class="primary">Enregistrer</button></form>').join('');
 area.innerHTML=`<section class="panel">${content}<p role="alert" class="error"></p></section>`;
 if(area.querySelector('#order-search')){const filter=()=>{const query=area.querySelector('#order-search').value.toLocaleLowerCase('fr'),status=area.querySelector('#order-status').value;area.querySelectorAll('[data-order-status]').forEach(row=>{row.hidden=!!((status&&row.dataset.orderStatus!==status)||!row.textContent.toLocaleLowerCase('fr').includes(query));});};area.querySelector('#order-search').oninput=filter;area.querySelector('#order-status').onchange=filter;}
 area.querySelectorAll('[data-method]').forEach(f=>f.onsubmit=e=>{e.preventDefault();run('payment-method',{id:f.dataset.method,status:f.elements.status.value,instructions:f.elements.instructions.value});});
 area.querySelector('#commercial-settings')?.addEventListener('submit',e=>{e.preventDefault();const plans=[...e.target.querySelectorAll('[data-plan]')].map(f=>({id:f.dataset.plan,limit:f.querySelector('[name=limit]').value===''?null:Number(f.querySelector('[name=limit]').value),unlimited:f.querySelector('[name=unlimited]').checked}));run('commercial-settings',{plans,planChange:e.target.elements.planChange.value||null});});
 area.querySelector('#promotion')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);run('promotion',{name:f.get('name'),code:f.get('code'),type:f.get('type'),value:Number(f.get('value'))});});
 area.querySelectorAll('[data-decision]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const approve=e.submitter.value==='approve',reason=f.elements.reason.value;if(!approve&&!reason.trim()){area.querySelector('[role=alert]').textContent='Indiquez le motif du refus.';return;}run('decision',{orderId:f.dataset.decision,approve,reason});});
 area.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>run('moderate-review',{id:b.dataset.review,status:b.dataset.status}));
 area.querySelectorAll('[data-proof]').forEach(b=>b.onclick=async()=>{try{const {url}=await api('proof-read',{orderId:b.dataset.proof});const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){area.querySelector('[role=alert]').textContent=e.message;}});
}
