import {orderRequest,clearOrderRequest} from '../order-request.js';
export async function interventionsPanel(area,{api,esc}){
 const data=await api('admin');
 area.innerHTML='<section class="panel"><h2>Interventions administratives</h2><p>Ces actions exceptionnelles sont journalisées. Les paiements continuent à être traités dans Commandes.</p><form id="intervention-form"><label>Client<select name="organizationId" required><option value="">Choisir une activité</option>'+data.clients.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select></label><p id="intervention-status" role="status"></p><label>Action<select name="operation"><option value="subscription">Ajouter une période administrative</option><option value="write_status">Suspendre ou rétablir les écritures</option></select></label><fieldset id="intervention-subscription"><legend>Période à ajouter après les droits acquis</legend><label>Formule<select name="plan"><option value="avance">Avancé</option><option value="vip">VIP</option></select></label><label>Durée<select name="months"><option value="1">1 mois</option><option value="3">3 mois</option><option value="6">6 mois</option><option value="12">12 mois</option></select></label><p>La période commence après toutes les périodes déjà accordées, ou maintenant si aucune ne reste. Aucun paiement n’est enregistré par cette action. Un changement Avancé/VIP exige la règle « à l’expiration » configurée dans Paramètres.</p></fieldset><fieldset id="intervention-write" hidden><legend>Statut des nouvelles écritures</legend><label>État<select name="suspended"><option value="true">Suspendre les nouvelles écritures</option><option value="false">Rétablir les nouvelles écritures</option></select></label><p>La consultation reste disponible. Aucune donnée ni période acquise n’est supprimée. La suspension ne décale pas les dates d’abonnement. Un appareil hors ligne prendra connaissance de cette mesure à sa reconnexion ; le serveur refusera alors les écritures en attente.</p></fieldset><label>Motif de l’intervention<textarea name="reason" required minlength="5" maxlength="2000"></textarea></label><p>Le motif sera également communiqué au client dans ses notifications internes.</p><button class="primary">Appliquer et journaliser l’intervention</button><p class="error" role="alert"></p></form><div id="intervention-result" role="status"></div></section>';
 const form=area.querySelector('form'),operation=form.elements.operation;
 operation.onchange=()=>{area.querySelector('#intervention-subscription').hidden=operation.value!=='subscription';area.querySelector('#intervention-write').hidden=operation.value!=='write_status';};
 form.elements.organizationId.onchange=()=>{const client=data.clients.find(c=>c.id===form.elements.organizationId.value);area.querySelector('#intervention-status').textContent=client?(client.write_suspended?'Nouvelles écritures actuellement suspendues.':'Nouvelles écritures autorisées sous réserve d’abonnement actif.') :'';};
 form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const f=new FormData(form),body={organizationId:f.get('organizationId'),operation:f.get('operation'),reason:f.get('reason').trim()};if(body.operation==='subscription'){body.plan=f.get('plan');body.months=Number(f.get('months'));}else body.suspended=f.get('suspended')==='true';const key='admin:'+body.organizationId;
 try{const {idempotencyKey,...payload}=orderRequest(sessionStorage,key,body);const result=await api('admin-intervention',{...payload,id:idempotencyKey});clearOrderRequest(sessionStorage,key);await interventionsPanel(area,{api,esc});area.querySelector('#intervention-result').textContent=result.subscriptionId?'Période ajoutée du '+new Date(result.startsAt).toLocaleString('fr-FR')+' au '+new Date(result.endsAt).toLocaleString('fr-FR')+'. Intervention journalisée.':'Statut enregistré et intervention journalisée.';}catch(error){form.querySelector('.error').textContent=error.message;button.disabled=false;}}
}
