export async function membersPanel(area,{api,esc}){
 const data=await api('members');
 const vehicles=data.vehicles.map(v=>`<label><input type="checkbox" name="vehicle" value="${esc(v.id)}"> ${esc(v.name||'Véhicule')}</label>`).join('');
 const refresh=()=>membersPanel(area,{api,esc});
 area.innerHTML=`<section class="panel"><h2>Accès en lecture seule</h2><p>Invitez une personne à consulter votre activité. Elle devra utiliser une adresse e-mail confirmée identique à celle de l’invitation. La capacité dépend des paramètres de votre formule.</p><form id="invite-form"><label>Adresse e-mail<input name="email" type="email" required maxlength="254"></label><label><input type="checkbox" name="all" checked> Tous les véhicules</label><fieldset><legend>Ou sélectionnez les véhicules autorisés</legend>${vehicles||'<p>Aucun véhicule enregistré.</p>'}</fieldset><button class="primary">Créer l’invitation</button><p role="alert" class="error"></p></form><div id="invite-link"></div><h3>Invitations</h3>${data.invitations.map(i=>{const status=i.status==='pending'&&Date.parse(i.expires_at)<=Date.now()?'expired':i.status;return `<article class="record-card"><strong>${esc(i.email)}</strong><span>${esc({pending:'En attente',accepted:'Acceptée',cancelled:'Annulée',expired:'Expirée'}[status])}</span>${status==='pending'?`<button data-copy="${esc(i.token)}">Afficher le lien</button><button data-cancel="${esc(i.id)}">Annuler</button>`:''}<small>Expiration : ${new Date(i.expires_at).toLocaleDateString('fr-FR')}</small></article>`;}).join('')||'<p>Aucune invitation.</p>'}<h3>Utilisateurs secondaires</h3>${data.members.filter(m=>m.role==='viewer').map(m=>`<article class="record-card"><strong>Lecteur ${esc(m.user_id.slice(0,8))}</strong><p>${m.active?'Actif':'Désactivé'} · ${m.all_vehicles?'Tous les véhicules':data.scopes.filter(s=>s.user_id===m.user_id).length+' véhicule(s)'}</p><button data-edit="${esc(m.user_id)}">Modifier les véhicules autorisés</button><button data-member="${esc(m.user_id)}">${m.active?'Révoquer l’accès':'Réactiver l’accès'}</button></article>`).join('')||'<p>Aucun lecteur rattaché.</p>'}<p id="member-error" role="alert"></p></section>`;
 const showLink=token=>{const link=new URL('/client',location.origin);link.searchParams.set('invitation',token);area.querySelector('#invite-link').innerHTML=`<label>Lien à transmettre au destinataire<input readonly value="${esc(link.href)}"></label><p>Valable sept jours. Aucun e-mail n’est envoyé automatiquement.</p>`;};
 area.querySelector('#invite-form').onsubmit=async e=>{e.preventDefault();const f=e.target,button=f.querySelector('button');button.disabled=true;try{const values=new FormData(f);const invitation=await api('invite',{email:values.get('email'),allVehicles:values.has('all'),vehicleIds:values.getAll('vehicle')});await refresh();showLink(invitation.token);}catch(error){f.querySelector('.error').textContent=error.message;}finally{button.disabled=false;}};
 area.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>showLink(b.dataset.copy));
 area.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await api('cancel-invitation',{id:b.dataset.cancel});await refresh();}catch(e){area.querySelector('#member-error').textContent=e.message;}});
 area.querySelectorAll('[data-member]').forEach(b=>b.onclick=async()=>{const m=data.members.find(x=>x.user_id===b.dataset.member);try{await api('member-access',{userId:m.user_id,active:!m.active,allVehicles:m.all_vehicles,vehicleIds:data.scopes.filter(s=>s.user_id===m.user_id).map(s=>s.vehicle_id)});await refresh();}catch(e){area.querySelector('#member-error').textContent=e.message;}});
 area.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{
  const m=data.members.find(x=>x.user_id===b.dataset.edit),assigned=data.scopes.filter(x=>x.user_id===m.user_id).map(x=>x.vehicle_id),dialog=document.createElement('dialog');
  dialog.innerHTML='<h2>Accès en lecture seule</h2><form><label><input type="checkbox" name="all" '+(m.all_vehicles?'checked':'')+'> Tous les véhicules</label><fieldset><legend>Véhicules autorisés</legend>'+data.vehicles.map(v=>'<label><input type="checkbox" name="vehicle" value="'+esc(v.id)+'" '+(assigned.includes(v.id)?'checked':'')+'> '+esc(v.name)+'</label>').join('')+'</fieldset><p class="error" role="alert"></p><button class="primary">Enregistrer</button><button type="button" id="close-access">Annuler</button></form>';
  area.append(dialog);dialog.setAttribute('aria-label',dialog.querySelector('h2')?.textContent||'Accès du membre');dialog.showModal();dialog.querySelector('#close-access').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api('member-access',{userId:m.user_id,active:m.active,allVehicles:f.has('all'),vehicleIds:f.getAll('vehicle')});dialog.close();await refresh();}catch(error){dialog.querySelector('.error').textContent=error.message;}};
 });

}
