export const orderStatus={awaiting_payment:'Paiement à effectuer',declared:'Paiement déclaré · En attente de vérification',reviewing:'Vérification en cours',approved:'Validée · Abonnement activé',rejected:'Paiement refusé',cancelled:'Annulée',expired:'Expirée'};
export async function paymentDetail(root,id,{api,client,esc,money,layout}){
 const {order,method,payment}=await api('order-detail',{id});
 const editable=['awaiting_payment','rejected','declared'].includes(order.status);
 root.innerHTML=layout(order.status==='approved'?'Votre abonnement est activé.':'Votre commande',`<p>Référence : <strong>${esc(order.reference)}</strong></p><p>${esc(orderStatus[order.status]||order.status)}</p><div class="order-summary"><div><span>Offre</span><b>${esc(order.plan_id)} · ${order.months} mois</b></div><div><span>Tarif officiel</span><b>${money(order.subtotal)}</b></div><div><span>Réduction</span><b>−${money(order.discount)}</b></div><div class="total"><span>Total</span><b>${money(order.total)}</b></div></div>${order.status==='approved'?'<p>Aucun paiement supplémentaire n’est demandé pour cette commande.</p>':`<h2>${esc(method.name)}</h2><p>${esc(method.instructions)}</p><p>La vérification est effectuée manuellement par notre équipe.</p>`}${payment?`<p>Référence transmise : ${esc(payment.reference)}</p>`:''}${payment?.proof_path?'<button id="open-proof">Consulter mon justificatif privé</button>':''}${editable?`<form id="declare-payment"><label>Référence du paiement<input name="reference" required maxlength="160" value="${esc(payment?.reference||'')}"></label><label>Justificatif (PDF, JPEG ou PNG, 5 Mo maximum)<input name="proof" type="file" accept="application/pdf,image/jpeg,image/png"></label><p>${payment?.proof_path?'Sans nouveau fichier, votre justificatif actuel est conservé.':''}</p><button class="primary">${payment?'Actualiser ma déclaration':'Déclarer mon paiement'}</button><p role="alert" class="error"></p></form>`:''}<p id="payment-message" role="alert"></p><a class="button" href="/client">Retour à mon espace</a>`);
 root.querySelector('#open-proof')?.addEventListener('click',async()=>{try{const {url}=await api('proof-read',{orderId:id});const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){root.querySelector('#payment-message').textContent=e.message;}});
 root.querySelector('#declare-payment')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,button=f.querySelector('button');button.disabled=true;try{
 const values=new FormData(f),file=values.get('proof');let proof=payment?.proof_path||null;
 if(file?.size){if(file.size>5*1024*1024)throw Error('Le justificatif dépasse 5 Mo.');const upload=await api('proof-upload',{orderId:id,type:file.type});const {error}=await client.storage.from('payment-proofs').uploadToSignedUrl(upload.path,upload.token,file);if(error)throw Error('Le justificatif n’a pas été envoyé. Réessayez.');proof=upload.path;}
 await api('declare-payment',{orderId:id,reference:values.get('reference'),proof});await paymentDetail(root,id,{api,client,esc,money,layout});root.querySelector('#payment-message').textContent='Déclaration enregistrée. Notre équipe vérifiera votre paiement.';
 }catch(error){f.querySelector('.error').textContent=error.message;}finally{button.disabled=false;}});
}
