export async function promotionsPanel(area,{api,esc,money}){
 const {promotions}=await api('admin');let editing=null;
 const dateValue=x=>x?new Date(x).toISOString().slice(0,16):'';
 area.innerHTML='<section class="panel"><h2>Promotions</h2><form id="promotion"><label>Nom<input name="name" maxlength="120" required></label><label>Code<input name="code" minlength="3" maxlength="50" required></label><label>Type<select name="type"><option value="percent">Pourcentage</option><option value="fixed">Montant KMF</option></select></label><label>Valeur<input name="value" type="number" min="0" step="0.01" required></label><label><input name="active" type="checkbox" checked> Actif</label><label>Début (UTC, facultatif)<input name="startsAt" type="datetime-local"></label><label>Fin (UTC, facultatif)<input name="endsAt" type="datetime-local"></label><label>Utilisations maximum (vide = illimité)<input name="maxUses" type="number" min="0" step="1"></label><label>Maximum par client (vide = illimité)<input name="maxPerClient" type="number" min="0" step="1"></label><label>Montant minimum KMF<input name="minimum" type="number" min="0" step="1" value="0"></label><fieldset><legend>Formules (aucune sélection = toutes)</legend>'+['avance','vip'].map(x=>'<label><input type="checkbox" name="plans" value="'+x+'"> '+x+'</label>').join('')+'</fieldset><fieldset><legend>Durées (aucune sélection = toutes)</legend>'+[1,3,6,12].map(x=>'<label><input type="checkbox" name="months" value="'+x+'"> '+x+' mois</label>').join('')+'</fieldset><button class="primary">Enregistrer la promotion</button><button type="button" id="new-promo">Nouvelle promotion</button><p class="error" role="alert"></p></form>'+promotions.map(p=>'<article class="record-card"><strong>'+esc(p.code)+'</strong><span>'+esc(p.name)+'</span><b>'+(p.type==='percent'?p.value+' %':money(p.value))+'</b><p>'+(p.active?'Actif':'Désactivé')+'</p><button data-promo="'+esc(p.id)+'">Modifier / désactiver</button></article>').join('')+'</section>';
 const form=area.querySelector('#promotion');
 area.querySelector('#new-promo').onclick=()=>{editing=null;form.reset();form.querySelector('.error').textContent='';};
 area.querySelectorAll('[data-promo]').forEach(b=>b.onclick=()=>{editing=promotions.find(p=>p.id===b.dataset.promo);const values={name:editing.name,code:editing.code,type:editing.type,value:editing.value,startsAt:dateValue(editing.starts_at),endsAt:dateValue(editing.ends_at),maxUses:editing.max_uses??'',maxPerClient:editing.max_per_client??'',minimum:editing.minimum};for(const [k,v]of Object.entries(values))form.elements[k].value=v;form.elements.active.checked=editing.active;for(const input of form.querySelectorAll('[name=plans]'))input.checked=editing.plans.includes(input.value);for(const input of form.querySelectorAll('[name=months]'))input.checked=editing.months.includes(Number(input.value));form.scrollIntoView({behavior:'smooth'});});
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('.primary');button.disabled=true;try{const f=new FormData(form),body={...(editing?{id:editing.id}:{}),name:f.get('name'),code:f.get('code'),type:f.get('type'),value:Number(f.get('value')),active:f.has('active'),plans:f.getAll('plans'),months:f.getAll('months').map(Number),minimum:Number(f.get('minimum'))};for(const k of ['maxUses','maxPerClient'])body[k]=f.get(k)===''?null:Number(f.get(k));for(const [k,column]of [['startsAt','starts_at'],['endsAt','ends_at']]){const value=f.get(k);body[k]=!value?null:editing&&value===dateValue(editing[column])?editing[column]:new Date(value+'Z').toISOString();}await api('promotion',body);await promotionsPanel(area,{api,esc,money});}catch(error){form.querySelector('.error').textContent=error.message;button.disabled=false;}};
}
