import test from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../src/domain/legacy-v1.js';
const rule={mode:'commission',commission:1000,tranche:5000,rule:'proportional',salary:0};
function day(overrides={}){return {id:'day',date:'2026-09-01',vehicleId:'v1',driverId:'d1',expected:5000,actual:5000,kmStart:0,kmEnd:100,status:'Travaillé',fuel:1500,fuelPayer:'driver',terms:{...rule},comment:'',incident:'',...overrides};}
function loan(overrides={}){return{id:'l1',vehicleId:'v1',lender:'Test',principal:120000,rate:0,count:12,payment:10000,frequency:'monthly',startDate:'2026-08-01',firstDue:'2026-09-01',fees:0,downPayment:0,vehiclePrice:120000,...overrides};}
test('commission proportionnelle, tranches complètes et salaire fixe',()=>{assert.equal(C.commission(4500,rule),900);assert.equal(C.commission(4500,{...rule,rule:'full'}),0);assert.equal(C.commission(11500,{...rule,rule:'full'}),2000);assert.equal(C.commission(5000,{...rule,mode:'fixed'}),0);assert.equal(C.commission(1,{...rule,commission:333,tranche:1000}),.33);});
test('résultat et trésorerie distincts, sans double comptabilisation',()=>{const s=C.blank();s.days=[day()];s.expenses=[{id:'e',vehicleId:'v1',date:'2026-09-01',category:'Assurance',description:'',method:'',comment:'',amount:500}];s.driverPayments=[{id:'p',driverId:'d1',date:'2026-09-01',amount:1000,comment:''}];let x=C.stats(s);assert.equal(x.profit,3500);assert.equal(x.balance,3500);s.days[0].fuelPayer='owner';x=C.stats(s);assert.equal(x.profit,2000);assert.equal(x.balance,2000);s.days[0].actual=6000;assert.equal(C.stats(s).balance,3000);s.expenses=[];assert.equal(C.stats(s).balance,3500);});
test('salaire dû et paiement sont séparés',()=>{const s=C.blank();s.days=[day({terms:{...rule,mode:'fixed'}})];s.wages=[{id:'w',driverId:'d1',date:'2026-09-01',amount:30000,terms:{...rule,mode:'fixed',salary:30000},comment:''}];assert.equal(C.stats(s).profit,-25000);assert.equal(C.stats(s).balance,5000);s.driverPayments=[{id:'p',driverId:'d1',date:'2026-09-10',amount:10000,comment:''}];assert.equal(C.stats(s).profit,-25000);assert.equal(C.stats(s).balance,-5000);assert.equal(C.stats(s).wage-C.stats(s).paid,20000);C.validate(s);});
test('paramètres modifiés sans réécrire les journées',()=>{const s=C.blank();s.days=[day()];s.drivers[0].commission=1200;assert.equal(C.stats(s).wage,1000);});
test('prêt : seul le capital payé réduit le capital restant',()=>{const s=C.blank();s.loans=[loan()];assert.equal(C.schedule(s,s.loans[0])[0].paid,0);assert.equal(C.loanBalance(s,'l1'),120000);s.loanPayments=[{id:'p',loanId:'l1',date:'2026-09-01',installment:1,principal:4000,interest:500,fees:100,comment:''}];assert.equal(C.loanBalance(s,'l1'),116000);assert.equal(C.stats(s).profit,-600);assert.equal(C.stats(s).balance,-4600);assert.equal(C.schedule(s,s.loans[0])[0].remaining,5500);});
test('mensualités sans taux et avec taux',()=>{assert.equal(C.monthlyPayment(120000,0,12),10000);assert.equal(C.monthlyPayment(1000000,12,12),88848.79);assert.equal(C.addPeriod('2026-01-31',1),'2026-02-28');assert.equal(C.addPeriod('2026-01-31',2),'2026-03-31');assert.equal(C.addPeriod('2026-09-01',1,'weekly'),'2026-09-08');});
test('apports, retraits et acquisition ne changent pas le résultat',()=>{const s=C.blank();s.movements=[{id:'a',date:'2026-09-01',type:'Apport propriétaire',ownerId:'o1',amount:10000,comment:''},{id:'b',date:'2026-09-01',type:'Retrait propriétaire',ownerId:'o2',amount:2000,comment:''}];assert.equal(C.stats(s).balance,8000);assert.equal(C.stats(s).profit,0);});
test('périodes : flux filtré et solde cumulé',()=>{const s=C.blank();s.days=[day(),day({id:'next',date:'2026-10-01',kmStart:100,kmEnd:200})];const x=C.stats(s,'2026-10-01','2026-10-31');assert.equal(x.revenue,5000);assert.equal(x.balance,10000);assert.equal(x.worked,1);});
test('simulation indépendante, seuil proportionnel et fixe',()=>{const p={daily:5000,days:26,target:5000,mode:'commission',salary:30000,commission:1000,tranche:5000,rule:'proportional',loan:50000,expenses:10000,maintenance:5000,insurance:5000,unexpected:0,other:0};const x=C.simulate(p);assert.equal(x.net,34000);assert.equal(x.wage,26000);assert.ok(Math.abs(x.breakEven-87500)<1);const y=C.simulate({...p,mode:'fixed'});assert.equal(y.net,30000);assert.ok(Math.abs(y.breakEven-100000)<1);});
test('sauvegarde complète : opérations ajoutées, effacement, restauration exacte',()=>{let s=C.demo();s.expenses.push({id:'new',date:C.today(),vehicleId:'v1',category:'Autre',description:'test supplémentaire',amount:1234,method:'Espèces',comment:''});s.movements.push({id:'new-m',date:C.today(),type:'Apport propriétaire',ownerId:'o1',amount:7777,comment:'test'});const before=C.stats(s),exported=JSON.stringify(C.backup(s)),records=s.days.length;s=C.blank();assert.equal(s.days.length,0);s=C.parseBackup(exported);assert.equal(s.days.length,records);assert.deepEqual(C.stats(s),before);assert.equal(s.expenses.at(-1).amount,1234);});
test('rejet JSON invalide, ancienne version, données incomplètes et négatives',()=>{assert.throws(()=>C.parseBackup('{'));const b=C.backup(C.blank());b.schemaVersion=0;assert.throws(()=>C.parseBackup(JSON.stringify(b)));b.schemaVersion=1;b.data.days=[day({actual:-1})];assert.throws(()=>C.parseBackup(JSON.stringify(b)));b.data.days=[day()];delete b.data.days[0].terms;assert.throws(()=>C.parseBackup(JSON.stringify(b)));});
test('contrôle des références, doublons, dates et kilométrage',()=>{const s=C.blank();s.days=[day(),day({id:'d2'})];assert.throws(()=>C.validate(s));s.days=[day({date:'2026-02-30'})];assert.throws(()=>C.validate(s));s.days=[day({vehicleId:'missing'})];assert.throws(()=>C.validate(s));s.days=[day(),day({id:'d2',date:'2026-09-02',kmStart:50,kmEnd:150})];assert.throws(()=>C.validate(s));s.days=[day({status:'Repos'})];assert.throws(()=>C.validate(s));});
test('le capital ne peut pas être remboursé au-delà du prêt',()=>{const s=C.blank();s.loans=[loan()];s.loanPayments=[{id:'p',loanId:'l1',date:'2026-09-01',installment:1,principal:130000,interest:0,fees:0,comment:''}];assert.throws(()=>C.validate(s));});
test('démonstration cohérente et base vide valides',()=>{const s=C.demo();C.validate(s);assert.ok(s.days.length>30);assert.ok(s.days.some(d=>d.status==='Repos'));assert.ok(s.days.some(d=>d.actual<d.expected));assert.ok(s.days.some(d=>d.actual>d.expected));C.validate(C.blank());});
test('seuil de rentabilité avec tranches complètes : premier palier atteignable',()=>{const p={daily:5000,days:1,target:5000,mode:'commission',salary:0,commission:1000,tranche:5000,rule:'full',loan:4500,expenses:0,maintenance:0,insurance:0,unexpected:0,other:0};assert.equal(C.simulate(p).breakEven,4500);assert.equal(C.simulate({...p,loan:5000}).breakEven,6000);assert.equal(C.simulate({...p,loan:0}).breakEven,0);});
test('salaire mensuel dupliqué refusé',()=>{const s=C.blank();const w={id:'w',driverId:'d1',date:'2026-09-01',amount:30000,terms:{...rule,mode:'fixed',salary:30000},comment:''};s.wages=[w,{...w,id:'w2',date:'2026-09-20'}];assert.throws(()=>C.validate(s));});
test('échéancier : dernière échéance ajuste les arrondis et aucun paiement supposé',()=>{const s=C.blank();s.loans=[loan({principal:1000000,rate:12,count:12,payment:C.monthlyPayment(1000000,12,12)})];const schedule=C.schedule(s,s.loans[0]);assert.equal(C.sum(schedule,e=>e.principal),1000000);assert.equal(schedule.at(-1).balance,0);assert.ok(schedule.every(e=>e.paid===0));});
