export const VERSION=2;
export const today=()=>new Date().toLocaleDateString('en-CA');
export const uid=()=>crypto.randomUUID();
export const round=n=>Math.round((n+Number.EPSILON)*100)/100;
export const sum=(a,f=x=>x.amount)=>round(a.reduce((s,x)=>s+f(x),0));
export const inPeriod=(x,from,to)=>x.date>=from&&x.date<=to;
export const collections=['vehicles','drivers','days','expenses','maintenance','loans','loanPayments','wages','driverPayments','movements','owners','loanVehicles'];
export const categories=['Entretien','Réparation','Assurance','Pneus','Vidange','Pièces','Taxes','Visite technique','Nettoyage','Carburant','Autre'];
export function blank(){return {schemaVersion:VERSION,revision:0,demo:false,settings:{currency:'KMF',target:5000,workdays:26,fuelPayer:'driver',categories:[...categories],lastBackup:null},vehicles:[{id:'v1',name:'Mon véhicule',plate:'',brand:'',model:'',year:2026,purchasePrice:0,purchaseDate:today(),initialKm:0,status:'Actif',notes:''}],drivers:[{id:'d1',name:'Mon chauffeur',phone:'',startDate:today(),status:'Actif',mode:'commission',salary:0,commission:1000,tranche:5000,rule:'proportional',notes:''}],owners:[{id:'o1',name:'Propriétaire 1'},{id:'o2',name:'Propriétaire 2'}],days:[],expenses:[],maintenance:[],loans:[],loanPayments:[],wages:[],driverPayments:[],movements:[],loanVehicles:[]};}
export function commission(amount,terms){if(terms.mode!=='commission')return 0;return round((terms.rule==='full'?Math.floor(amount/terms.tranche):amount/terms.tranche)*terms.commission);}
export function terms(driver){return {mode:driver.mode,commission:driver.commission,tranche:driver.tranche,rule:driver.rule,salary:driver.salary};}
export function dayWage(d){return d.status==='Travaillé'?commission(d.actual,d.terms):0;}
export function ledger(s){return [
...s.days.flatMap(d=>[{id:d.id+'-in',source:'days',sourceId:d.id,date:d.date,label:'Versement · '+d.status,amount:d.actual},...(d.fuelPayer==='owner'&&d.fuel>0?[{id:d.id+'-fuel',source:'days',sourceId:d.id,date:d.date,label:'Carburant propriétaire',amount:-d.fuel}]:[])]),
...s.expenses.map(e=>({id:e.id,source:'expenses',sourceId:e.id,date:e.date,label:e.category+' · '+e.description,amount:-e.amount})),
...s.maintenance.map(e=>({id:e.id,source:'maintenance',sourceId:e.id,date:e.date,label:'Entretien · '+e.type,amount:-e.cost})),
...s.loanPayments.map(e=>({id:e.id,source:'loanPayments',sourceId:e.id,date:e.date,label:'Prêt · capital et intérêts',amount:-round(e.principal+e.interest+e.fees)})),
...s.driverPayments.map(e=>({id:e.id,source:'driverPayments',sourceId:e.id,date:e.date,label:'Paiement chauffeur',amount:-e.amount})),
...s.movements.map(e=>({id:e.id,source:'movements',sourceId:e.id,date:e.date,label:e.type+' · '+(s.owners.find(o=>o.id===e.ownerId)?.name||'')+' '+e.comment,amount:['Apport propriétaire','Autre entrée','Déblocage du prêt'].includes(e.type)?e.amount:-e.amount}))
].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));}
export function stats(s,from='0000-01-01',to='9999-12-31'){
const filter=a=>a.filter(x=>inPeriod(x,from,to)),days=filter(s.days),expenses=filter(s.expenses),maint=filter(s.maintenance),lp=filter(s.loanPayments),cash=filter(ledger(s));
const revenue=sum(days,d=>d.actual),expected=sum(days,d=>d.expected),fuel=sum(days,d=>d.fuelPayer==='owner'?d.fuel:0),costs=round(sum(expenses)+sum(maint,m=>m.cost)+fuel),wage=round(sum(days,dayWage)+sum(filter(s.wages))),interest=sum(lp,p=>p.interest+p.fees),loanPaid=sum(lp,p=>p.principal+p.interest+p.fees),paid=sum(filter(s.driverPayments));
return {revenue,expected,gap:round(revenue-expected),costs,wage,paid,interest,loanPaid,profit:round(revenue-costs-wage-interest),cashChange:sum(cash),balance:sum(ledger(s).filter(x=>x.date<=to)),inflow:sum(cash.filter(x=>x.amount>0)),outflow:-sum(cash.filter(x=>x.amount<0)),worked:days.filter(x=>x.status==='Travaillé').length,idle:days.filter(x=>x.status!=='Travaillé').length,km:sum(days,x=>x.kmEnd-x.kmStart)};
}
export function loanBalance(s,id){const l=s.loans.find(l=>l.id===id);return round(l.principal-sum(s.loanPayments.filter(p=>p.loanId===id),p=>p.principal));}
export function monthlyPayment(principal,rate,count,frequency='monthly'){const r=rate/100/(frequency==='weekly'?52:12);return count>0?round(r?principal*r/(1-Math.pow(1+r,-count)):principal/count):0;}
export function addPeriod(date,n,frequency='monthly'){const [y,m,d]=date.split('-').map(Number);let t;if(frequency==='weekly')t=new Date(Date.UTC(y,m-1,d+n*7));else{t=new Date(Date.UTC(y,m-1+n,1));t.setUTCDate(Math.min(d,new Date(Date.UTC(t.getUTCFullYear(),t.getUTCMonth()+1,0)).getUTCDate()));}return t.toISOString().slice(0,10);}
export function schedule(s,l){let balance=l.principal;const rate=l.rate/100/(l.frequency==='weekly'?52:12);return Array.from({length:l.count},(_,i)=>{const interest=round(balance*rate),payment=i===l.count-1?round(balance+interest):Math.min(l.payment,round(balance+interest));const principal=round(Math.max(0,payment-interest));balance=round(Math.max(0,balance-principal));const paid=sum(s.loanPayments.filter(p=>p.loanId===l.id&&p.installment===i+1),p=>p.principal+p.interest);return {number:i+1,date:addPeriod(l.firstDue,i,l.frequency),payment,principal,interest,balance,paid,remaining:round(Math.max(0,payment-paid))};});}
export function simulate(p){const revenue=round(p.daily*p.days),wage=p.mode==='fixed'?p.salary:round(commission(p.daily,{mode:p.mode,commission:p.commission,tranche:p.tranche,rule:p.rule})*p.days),charges=round(p.expenses+p.maintenance+p.insurance+p.unexpected+p.other),profit=round(revenue-wage-charges),net=round(profit-p.loan);let threshold;if(p.mode==='fixed')threshold=round(charges+p.loan+p.salary);else {const required=(charges+p.loan)/p.days;if(p.rule==='full'){const k=Math.max(0,Math.ceil((required-(p.tranche-.01))/(p.tranche-p.commission)));const daily=Math.max(k*p.tranche,Math.ceil((required+k*p.commission)*100-1e-7)/100);threshold=round(daily*p.days);}else{let daily=Math.ceil(required/(1-p.commission/p.tranche)*100)/100;if(!Number.isFinite(daily)||daily>1e10){threshold=null;}else{while(daily-commission(daily,p)<required-1e-8)daily=round(daily+.01);while(daily>=.01&&round(daily-.01)-commission(round(daily-.01),p)>=required-1e-8)daily=round(daily-.01);threshold=round(daily*p.days);}}}return {revenue,wage,charges,profit,net,margin:revenue?round(net/revenue*100):0,breakEven:threshold,targetGap:round(revenue-p.target*p.days)};}
const fail=m=>{throw Error(m);};
export function validate(s){
if(!s||s.schemaVersion!==VERSION)fail('Version du schéma non prise en charge. Import annulé.');
const str=(v,n)=>{if(typeof v!=='string'||v.length>20000)fail('Texte invalide : '+n);};
const num=(v,n,min=0)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>1e12||Math.abs(v*100-Math.round(v*100))>0.001)fail('Nombre invalide : '+n);};
const date=(v,n)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)fail('Date invalide : '+n);};
const one=(v,a,n)=>{if(!a.includes(v))fail('Valeur invalide : '+n);};
const rule=t=>{if(!t)fail('Règle de rémunération absente');one(t.mode,['fixed','commission'],'rémunération');one(t.rule,['proportional','full'],'commission');num(t.commission,'commission');num(t.tranche,'tranche',0.01);num(t.salary,'salaire');if(t.commission>=t.tranche)fail('La commission doit être inférieure à sa tranche.');};
if(typeof s.demo!=='boolean'||!Number.isInteger(s.revision)||s.revision<0)fail('Métadonnées invalides');
for(const c of collections){if(!Array.isArray(s[c])||s[c].length>100000)fail('Collection invalide : '+c);const ids=new Set();for(const x of s[c]){if(!x||typeof x!=='object')fail('Enregistrement invalide');str(x.id,'id');if(!x.id||ids.has(x.id))fail('Identifiant vide ou dupliqué');ids.add(x.id);}}
if(!s.vehicles.length||!s.drivers.length||!s.owners.length)fail('Un véhicule, un chauffeur et un propriétaire sont nécessaires.');
const ref=(c,id)=>{if(!s[c].some(x=>x.id===id))fail('Référence absente : '+c);};
if(!s.settings)fail('Paramètres absents');str(s.settings.currency,'devise');if(!/^[A-Z]{3}$/.test(s.settings.currency))fail('Devise : trois lettres majuscules requises');num(s.settings.target,'objectif');num(s.settings.workdays,'jours',1);if(!Number.isInteger(s.settings.workdays)||s.settings.workdays>31)fail('Le nombre indicatif de jours doit être compris entre 1 et 31.');one(s.settings.fuelPayer,['owner','driver'],'carburant');if(!Array.isArray(s.settings.categories)||!s.settings.categories.length)fail('Catégories absentes');s.settings.categories.forEach(c=>str(c,'catégorie'));if(s.settings.lastBackup!==null&&(typeof s.settings.lastBackup!=='string'||isNaN(Date.parse(s.settings.lastBackup))))fail('Date de sauvegarde invalide');
for(const v of s.vehicles){['name','plate','brand','model','status','notes'].forEach(k=>str(v[k],k));['year','purchasePrice','initialKm'].forEach(k=>num(v[k],k));date(v.purchaseDate,'achat');}
for(const d of s.drivers){['name','phone','status','notes'].forEach(k=>str(d[k],k));date(d.startDate,'début chauffeur');rule(d);}
for(const o of s.owners)str(o.name,'propriétaire');
const dates=new Set();for(const d of s.days){date(d.date,'journée');ref('vehicles',d.vehicleId);ref('drivers',d.driverId);const key=d.vehicleId+d.date;if(dates.has(key))fail('Une seule journée est autorisée par véhicule et par date.');dates.add(key);['expected','actual','fuel','kmStart','kmEnd'].forEach(k=>num(d[k],k));if(d.kmEnd<d.kmStart)fail('Le kilométrage arrivée doit être supérieur ou égal au départ.');one(d.status,['Travaillé','Repos','Panne','Entretien','Indisponible','Autre'],'journée');one(d.fuelPayer,['owner','driver'],'carburant');str(d.comment,'commentaire');str(d.incident,'incident');rule(d.terms);if(d.status!=='Travaillé'&&(d.actual||d.expected))fail('Une journée non travaillée doit avoir un attendu et un versement nuls.');}
const ordered=[...s.days].sort((a,b)=>a.date.localeCompare(b.date));const kms=new Map(s.vehicles.map(v=>[v.id,v.initialKm]));for(const d of ordered){if(d.kmStart<kms.get(d.vehicleId))fail('Kilométrage incohérent avec une journée antérieure ou le kilométrage initial.');kms.set(d.vehicleId,d.kmEnd);}
for(const e of s.expenses){date(e.date,'dépense');ref('vehicles',e.vehicleId);num(e.amount,'montant',0.01);['category','description','method','comment'].forEach(k=>str(e[k],k));if(['prêt','rémunération chauffeur','paiement chauffeur'].includes(e.category.toLowerCase()))fail('Utilisez le module Prêt ou Chauffeur pour ce paiement.');}
for(const m of s.maintenance){date(m.date,'entretien');ref('vehicles',m.vehicleId);['cost','km','nextKm'].forEach(k=>num(m[k],k));['type','provider','comment'].forEach(k=>str(m[k],k));if(m.nextDate)date(m.nextDate,'prochain entretien');}
for(const l of s.loans){str(l.lender,'prêteur');['principal','rate','payment','downPayment','vehiclePrice','fees'].forEach(k=>num(l[k],k));num(l.count,'échéances',1);if(!Number.isInteger(l.count)||l.count>1200)fail('Nombre d’échéances invalide');date(l.startDate,'début prêt');date(l.firstDue,'première échéance');one(l.frequency,['monthly','weekly'],'fréquence');if(l.payment<=round(l.principal*l.rate/100/(l.frequency==='weekly'?52:12)))fail('La mensualité ne couvre pas les intérêts.');if(loanBalance(s,l.id)<0)fail('Le capital payé dépasse le montant emprunté.');}
for(const p of s.loanPayments){ref('loans',p.loanId);date(p.date,'paiement prêt');['principal','interest','fees'].forEach(k=>num(p[k],k));str(p.comment,'commentaire');const l=s.loans.find(l=>l.id===p.loanId);if(!Number.isInteger(p.installment)||p.installment<1||p.installment>l.count)fail('Échéance invalide');if(p.principal+p.interest+p.fees<=0)fail('Le paiement doit être positif');}
const wm=new Set();for(const w of s.wages){ref('vehicles',w.vehicleId);ref('drivers',w.driverId);date(w.date,'salaire');num(w.amount,'salaire');str(w.comment,'commentaire');rule(w.terms);if(w.terms.mode!=='fixed')fail('Le salaire mensuel nécessite une règle fixe');const key=w.driverId+w.date.slice(0,7);if(wm.has(key))fail('Un salaire existe déjà pour ce mois.');wm.add(key);}
for(const p of s.driverPayments){ref('vehicles',p.vehicleId);ref('drivers',p.driverId);date(p.date,'paiement chauffeur');num(p.amount,'paiement',0.01);str(p.comment,'commentaire');}
for(const m of s.movements){if(m.vehicleId)ref('vehicles',m.vehicleId);if(m.loanId)ref('loans',m.loanId);date(m.date,'trésorerie');num(m.amount,'montant',0.01);str(m.comment,'commentaire');one(m.type,['Apport propriétaire','Retrait propriétaire','Autre entrée','Autre sortie','Achat véhicule','Déblocage du prêt'],'mouvement');if(m.type.includes('propriétaire'))ref('owners',m.ownerId);}
return s;
}
export function backup(s){validate(s);return {format:'NR-TRANS',formatVersion:2,schemaVersion:VERSION,appVersion:'2.0.0',createdAt:new Date().toISOString(),data:structuredClone(s)};}
export function parseBackup(text){let b;try{b=JSON.parse(text);}catch{fail('Fichier JSON invalide. Vos données sont conservées.');}if(b?.format!=='NR-TRANS'||b.formatVersion!==2||b.schemaVersion!==VERSION)fail('Format ou version incompatible. Aucune donnée modifiée.');if(typeof b.createdAt!=='string'||isNaN(Date.parse(b.createdAt)))fail('Métadonnées de sauvegarde invalides');return validate(b.data);}
